version: "3.9"

services:

  api:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - VIRUS_API_KEY=${VIRUS_API_KEY}
    networks:
      - appnet

  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - appnet

networks:
  appnet: